### ISSUE TITLE
Tuple - question 2

### ISSUE THREAD

**Issue by amymhaddad** [amymhaddad/exercises_for_programmers#37]
Question 1: 

len(((1, 2),)) --->evaluates to 1.

I thought that the comma on the far right denoted a place holder for a value, so the len would be 2? Why doesn't the comma count as a value?
-----> ,))

Question 2: 

len((1, 2,(1, 2, 3)))

Why is there a comma after the two in the parent tuple ----> (1, 2,.... 
And there's not a comma after the child tuple ----> (1,2,3)....

Is the comma in the first instance to tell Python that you're not multiplying the parent 2 to the child ()? That is, to tell python that 2 is a number in a () and not a math operation?

**Comment by paulghaddad** [comment]
Question 1: The comma just allows Python to distinguish a tuple that contains a single value (singleton tuple, such as `(1, )` versus a calculation involving parentheses in Python, such as `(1)`. Without the comma, Python couldn't tell the difference. So the tuple above has a single item, and the comma simply says to Python that this is a tuple, and not a normal parentheses.

Question 2: 

This tuple, `(1, 2,(1, 2, 3))` has three separate values: `1`, `2` and the tuple `(1, 2, 3)`. There's a comma after the `2` because it separates items in the tuple. The parent tuple is not a singleton tuple with one value, so it's not necessary to use an ending comma.

**Comment by amymhaddad** [comment]
Ok, so regarding question 2, could I write the tuple like this: (1, 2(1, 2, 3) and not use the comma? Or is it best practice to add that comma in? It looks like many of the practice problems I see, the comma is added in to the parent tuple even if it's not a singleton.
